### ISSUE TITLE
How to deploy a program?

### ISSUE THREAD

**Issue by olehmisar** [puzzlehq/puzzle-sdk#27]
As I understand, `requestCreateEvent` with `EventType.Deploy` should be used to deploy a program. Where do I put source code? Other options include `programId`, `functionId` etc but nothing similar to `programSource`.
```js
import { requestCreateEvent } from '@puzzlehq/sdk';
import myProgramSource from './myProgram?raw';

await requestCreateEvent({
  type: EventType.Deploy,
  // where to put myProgramSource?
});
```

**Comment by jonandgon** [comment]
So we currently are not supporting ALEO contract deployment via our SDK. The account abtraction + delegated proving does not work for deployments. There's no easy workaround for this right now beyond sending private keys to our servers and we don't want to do that :) 

We will announce when we implement this!

For now, It's recommended to deploy your programs via [snarkOS](https://github.com/AleoHQ/snarkOS/tree/testnet3), especially if your program has imports. We don't recommend using [aleo.tools](https://aleo.tools/develop) as the WASM doesn't support deploying programs with imports.

**Comment by olehmisar** [comment]
I am fine with "sending private keys". The transaction proving speed is so superior on your provers compared to my local machine (which is already quite fast), that I would accept sending my private key to your server (since this is a testnet, sending private keys is obviously not a security risk)
